name: qr_code_dart_scan
description: A QR code scanner that works on both iOS and Android using dart decoder.
version: 0.9.3
publish_to: none
homepage: https://github.com/RafaelBarbosatec/qr_code_dart_scan

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera:
    git: https://github.com/kumsumit/camera.git
  zxing_lib: ^1.1.2
  image: ^4.3.0
  camera_platform_interface:
    git: https://github.com/kumsumit/camera_platform_interface.git
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter: